import Head from 'next/head'
import { Box } from '@mui/material'
import { Navigation } from '@/components/navigation'
import LoginSection from '../sections/admin/Login'
import SideNavigation from '@/components/navigation/LoggedInNavigation'
import { useAuth } from '@/hooks/use-auth'
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { useEffect, useState } from 'react'


const Page = () => {
  const data = useAuth();
  const [errorMessage, setErrorMessages] = useState(sessionStorage['errorMessage'])

  useEffect(() => {
    if(errorMessage){
      toast.error(errorMessage)
      setErrorMessages("")
      delete sessionStorage['errorMessage']
    }
  }, [])
  
  return (
    <>
      <Head>
        <title>Angendar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Box>
            <ToastContainer />
            <Navigation session={data.isAuthenticated}/>
            {data.isAuthenticated ? <SideNavigation/> : <LoginSection /> }
          </Box>
      </main>
    </>
  )
}

Page.getLayout = (page) => (
    page
);

export default Page;


