import Head from 'next/head'

import { Inter } from 'next/font/google'
import { Box } from '@mui/material'
import { Navigation } from '@/components/navigation'
import { useSession, signIn, signOut } from "next-auth/react"

import LoginSection from '../sections/admin/Login'
const inter = Inter({ subsets: ['latin'] })

import Authentication3Comp from '../components/quest/Authentication3'
import SideNavigation from '@/components/navigation/LoggedInNavigation'
import { useState } from 'react'

export default function Home() {
  // const { data: session } = useSession()
  const [session, setSession] = useState(false)
  return (
    <>
      <Head>
        <title>Angendar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Box>
            <Navigation session={session}/>
            
            {session ? <SideNavigation/> : <LoginSection session={session} setSession={setSession}/> }
          </Box>
      </main>
    </>
  )
}
